// This file wires the AI invocation-log controller and response projection helpers.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package invocation

import (
	"lina-core/pkg/apitime"
	"lina-plugin-linapro-ai-core/backend/api/invocation"
	v1 "lina-plugin-linapro-ai-core/backend/api/invocation/v1"
	aisvc "lina-plugin-linapro-ai-core/backend/internal/service/ai"
)

// ControllerV1 handles masked AI invocation-log APIs.
type ControllerV1 struct {
	aiSvc aisvc.Service // aiSvc owns invocation-log query logic.
}

// NewV1 creates and returns a new AI invocation-log controller instance.
func NewV1(aiSvc aisvc.Service) invocation.IInvocationV1 {
	return &ControllerV1{aiSvc: aiSvc}
}

// toAPIInvocationItem converts a service invocation projection into API DTO shape.
func toAPIInvocationItem(item *aisvc.InvocationItem) *v1.InvocationItem {
	if item == nil {
		return nil
	}
	return &v1.InvocationItem{
		Id:             item.Id,
		RequestId:      item.RequestId,
		CapabilityType: item.CapabilityType,
		Purpose:        item.Purpose,
		TierCode:       item.TierCode,
		SourcePluginId: item.SourcePluginId,
		TenantId:       item.TenantId,
		UserId:         item.UserId,
		ProviderId:     item.ProviderId,
		ModelId:        item.ModelId,
		ProviderName:   item.ProviderName,
		ModelName:      item.ModelName,
		Protocol:       item.Protocol,
		ThinkingEffort: item.ThinkingEffort,
		Status:         item.Status,
		InputTokens:    item.InputTokens,
		OutputTokens:   item.OutputTokens,
		LatencyMs:      item.LatencyMs,
		ErrorCode:      item.ErrorCode,
		ErrorSummary:   item.ErrorSummary,
		CreatedAt:      milliValue(apitime.Milli(item.CreatedAt)),
	}
}

// milliValue projects optional millisecond timestamps to zero for absent fields.
func milliValue(value *int64) int64 {
	if value == nil {
		return 0
	}
	return *value
}
