// This file wires the AI model controller.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"lina-plugin-linapro-ai-core/backend/api/model"
	aisvc "lina-plugin-linapro-ai-core/backend/internal/service/ai"
)

// ControllerV1 handles provider model APIs.
type ControllerV1 struct {
	aiSvc aisvc.Service // aiSvc owns model management logic.
}

// NewV1 creates and returns a new AI model controller instance.
func NewV1(aiSvc aisvc.Service) model.IModelV1 {
	return &ControllerV1{aiSvc: aiSvc}
}
