// This file wires the AI provider controller and response projection helpers.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package provider

import (
	"lina-core/pkg/apitime"
	"lina-plugin-linapro-ai-core/backend/api/provider"
	v1 "lina-plugin-linapro-ai-core/backend/api/provider/v1"
	aisvc "lina-plugin-linapro-ai-core/backend/internal/service/ai"
)

// ControllerV1 handles AI provider and provider-owned model APIs.
type ControllerV1 struct {
	aiSvc aisvc.Service // aiSvc owns provider and model management logic.
}

// NewV1 creates and returns a new AI provider controller instance.
func NewV1(aiSvc aisvc.Service) provider.IProviderV1 {
	return &ControllerV1{aiSvc: aiSvc}
}

// toAPIProviderItem converts a service provider projection into API DTO shape.
func toAPIProviderItem(item *aisvc.ProviderItem) *v1.ProviderItem {
	if item == nil {
		return nil
	}
	return &v1.ProviderItem{
		Id:                item.Id,
		Name:              item.Name,
		WebsiteUrl:        item.WebsiteUrl,
		Remark:            item.Remark,
		OpenaiBaseUrl:     item.OpenaiBaseUrl,
		AnthropicBaseUrl:  item.AnthropicBaseUrl,
		ApiKeySecretRef:   item.ApiKeySecretRef,
		Enabled:           item.Enabled,
		ModelCount:        item.ModelCount,
		EnabledModelCount: item.EnabledModelCount,
		CreatedAt:         milliValue(apitime.Milli(item.CreatedAt)),
		UpdatedAt:         milliValue(apitime.Milli(item.UpdatedAt)),
	}
}

// toAPIModelItem converts a service model projection into API DTO shape.
func toAPIModelItem(item *aisvc.ModelItem) *v1.ModelItem {
	if item == nil {
		return nil
	}
	return &v1.ModelItem{
		Id:               item.Id,
		ProviderId:       item.ProviderId,
		CapabilityType:   item.CapabilityType,
		ModelName:        item.ModelName,
		Protocol:         item.Protocol,
		Source:           item.Source,
		SupportsThinking: item.SupportsThinking,
		SupportedEfforts: item.SupportedEfforts,
		MaxInputTokens:   item.MaxInputTokens,
		MaxOutputTokens:  item.MaxOutputTokens,
		Enabled:          item.Enabled,
		CreatedAt:        milliValue(apitime.Milli(item.CreatedAt)),
		UpdatedAt:        milliValue(apitime.Milli(item.UpdatedAt)),
	}
}

// milliValue projects optional millisecond timestamps to zero for absent fields.
func milliValue(value *int64) int64 {
	if value == nil {
		return 0
	}
	return *value
}
