// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package identity

import (
	"lina-core/pkg/plugin/capability/bizctxcap"
	"lina-plugin-linapro-oidc-core/backend/api/identity"
	identitysvc "lina-plugin-linapro-oidc-core/backend/internal/service/identity"
)

// ControllerV1 handles the current-user external identity binding API.
type ControllerV1 struct {
	identitySvc *identitysvc.Service // external identity linkage service
	bizCtxSvc   bizctxcap.Service    // current request business context
}

// NewV1 creates and returns a new external identity controller instance.
func NewV1(identitySvc *identitysvc.Service, bizCtxSvc bizctxcap.Service) identity.IIdentityV1 {
	return &ControllerV1{identitySvc: identitySvc, bizCtxSvc: bizCtxSvc}
}
