// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-ai-core/backend/internal/dao/internal"
)

// methodDefaultParamDao is the data access object for the table plugin_linapro_ai_method_default_param.
// You can define custom methods on it to extend its functionality as needed.
type methodDefaultParamDao struct {
	*internal.MethodDefaultParamDao
}

var (
	// MethodDefaultParam is a globally accessible object for table plugin_linapro_ai_method_default_param operations.
	MethodDefaultParam = methodDefaultParamDao{internal.NewMethodDefaultParamDao()}
)

// Add your custom methods and functionality below.
